pluginManagement {
    repositories {
        gradlePluginPortal()
        maven { url = 'https://maven.fabricmc.net/' }
        maven { url = 'https://repo.papermc.io/repository/maven-public/' }
    }
}

rootProject.name = 'ProjectKorra'
include 'common', 'bukkit', 'fabric'
include 'reference-checker'
project(':reference-checker').projectDir = file('build-tools/reference-checker')
