package com.projectkorra.projectkorra.platform.mc;

import com.projectkorra.projectkorra.platform.mc.block.data.BlockData;
import com.projectkorra.projectkorra.platform.mc.block.data.Levelled;
import com.projectkorra.projectkorra.platform.mc.block.data.type.Fire;

import java.util.Locale;
import java.util.function.Consumer;

public enum Material {
    ANVIL,
    LADDER,
    LIGHT,
    VINE,
    ACACIA_BUTTON,
    ACACIA_DOOR,
    ACACIA_TRAPDOOR,
    AIR,
    ARROW,
    BAKED_POTATO,
    BARRIER,
    BEDROCK,
    BEACON,
    BEEF,
    BEETROOTS,
    BIRCH_BUTTON,
    BIRCH_DOOR,
    BIRCH_TRAPDOOR,
    BLACKSTONE,
    BLAST_FURNACE,
    BOW,
    BUCKET,
    BUBBLE_COLUMN,
    CARROTS,
    CAULDRON,
    CAVE_AIR,
    CHAINMAIL_BOOTS,
    CHAINMAIL_CHESTPLATE,
    CHAINMAIL_HELMET,
    CHAINMAIL_LEGGINGS,
    CHEST,
    CHICKEN,
    CLOCK,
    COAL,
    COMPASS,
    CHORUS_FRUIT,
    COBBLESTONE,
    COD,
    PUFFERFISH,
    TROPICAL_FISH,
    DRAGON_EGG,
    END_PORTAL,
    END_PORTAL_FRAME,
    ENDER_CHEST,
    COOKED_BEEF,
    COOKED_CHICKEN,
    COOKED_COD,
    COOKED_MUTTON,
    COOKED_PORKCHOP,
    COOKED_RABBIT,
    COOKED_SALMON,
    CROSSBOW,
    DARK_OAK_BUTTON,
    DARK_OAK_DOOR,
    DARK_OAK_TRAPDOOR,
    DEEPSLATE,
    DIAMOND_AXE,
    DIAMOND_BOOTS,
    DIAMOND_CHESTPLATE,
    DIAMOND_HELMET,
    DIAMOND_HOE,
    DIAMOND_LEGGINGS,
    DIAMOND_PICKAXE,
    DIAMOND_SHOVEL,
    DIAMOND_SWORD,
    DIRT,
    DISPENSER,
    DRIED_KELP,
    DROPPER,
    FARMLAND,
    DEAD_BUSH,
    FIRE,
    FURNACE,
    GLASS_BOTTLE,
    GLOWSTONE,
    GOLD_INGOT,
    GOLD_NUGGET,
    GOLD_ORE,
    GOLDEN_AXE,
    GOLDEN_BOOTS,
    GOLDEN_CHESTPLATE,
    GOLDEN_HELMET,
    GOLDEN_HOE,
    GOLDEN_HORSE_ARMOR,
    GOLDEN_LEGGINGS,
    GOLDEN_PICKAXE,
    GOLDEN_SHOVEL,
    GOLDEN_SWORD,
    GRASS_BLOCK,
    GRAVEL,
    HEAVY_WEIGHTED_PRESSURE_PLATE,
    HOPPER,
    ICE,
    IRON_AXE,
    IRON_BARS,
    IRON_BLOCK,
    IRON_BOOTS,
    IRON_CHESTPLATE,
    IRON_DOOR,
    IRON_HELMET,
    IRON_HOE,
    IRON_HORSE_ARMOR,
    IRON_INGOT,
    IRON_LEGGINGS,
    IRON_NUGGET,
    IRON_PICKAXE,
    IRON_SHOVEL,
    IRON_SWORD,
    IRON_TRAPDOOR,
    JUKEBOX,
    LIGHT_WEIGHTED_PRESSURE_PLATE,
    JUNGLE_BUTTON,
    JUNGLE_DOOR,
    JUNGLE_TRAPDOOR,
    KELP,
    KELP_PLANT,
    LAVA,
    LEATHER_BOOTS,
    LEATHER_CHESTPLATE,
    LEATHER_HELMET,
    LEATHER_LEGGINGS,
    LEVER,
    LIGHT_BLUE_STAINED_GLASS,
    MAGMA_BLOCK,
    MELON,
    MUD,
    MUTTON,
    NETHERITE_AXE,
    NETHERITE_BOOTS,
    NETHERITE_CHESTPLATE,
    NETHERITE_HELMET,
    NETHERITE_HOE,
    NETHERITE_LEGGINGS,
    NETHERITE_PICKAXE,
    NETHERITE_SHOVEL,
    NETHERITE_SWORD,
    NETHERRACK,
    OAK_BUTTON,
    OAK_DOOR,
    OAK_LEAVES,
    OAK_TRAPDOOR,
    OBSIDIAN,
    ORANGE_STAINED_GLASS,
    PACKED_ICE,
    POPPED_CHORUS_FRUIT,
    PORKCHOP,
    POTATO,
    POTATOES,
    POTION,
    PUMPKIN,
    QUARTZ,
    RABBIT,
    RED_SAND,
    RED_SANDSTONE,
    REDSTONE_WALL_TORCH,
    ROOTED_DIRT,
    SALMON,
    SAND,
    SANDSTONE,
    SEAGRASS,
    SMOKER,
    SNOW,
    SNOW_BLOCK,
    SOUL_CAMPFIRE,
    SOUL_FIRE,
    SOUL_TORCH,
    SPONGE,
    SPRUCE_BUTTON,
    SPRUCE_DOOR,
    SPRUCE_TRAPDOOR,
    STICK,
    STONE,
    STONE_AXE,
    STONE_BUTTON,
    STONE_HOE,
    STONE_PICKAXE,
    STONE_SHOVEL,
    STONE_SWORD,
    SUGAR_CANE,
    TALL_GRASS,
    TALL_SEAGRASS,
    TORCH,
    TRIDENT,
    TURTLE_HELMET,
    VOID_AIR,
    WATER,
    WET_SPONGE,
    WHEAT,
    WHITE_STAINED_GLASS,
    WOODEN_AXE,
    WOODEN_HOE,
    WOODEN_PICKAXE,
    WOODEN_SHOVEL,
    WOODEN_SWORD,
    ACACIA_WOOD, AMETHYST_BLOCK, ANCIENT_DEBRIS, ANDESITE, ANDESITE_SLAB, ANDESITE_STAIRS,
    BASALT, BIG_DRIPLEAF, BLACK_CONCRETE, BLACK_CONCRETE_POWDER, BLACK_WOOL, BLOCK_RAW_GOLD,
    BLUE_GLAZED_TERRACOTTA, BLUE_ICE, BLUE_ORCHID, BLUE_TERRACOTTA, BLUE_WOOL, BONE_BLOCK,
    BRAIN_CORAL_BLOCK, BROWN_CONCRETE, BROWN_CONCRETE_POWDER, BROWN_MUSHROOM, BROWN_MUSHROOM_BLOCK,
    BROWN_TERRACOTTA, BROWN_WOOL, BUBBLE_CORAL_BLOCK, CACTUS, CACTUS_FLOWER, CALCITE, CAVE_VINES,
    CAVE_VINES_PLANT, CHAIN, CHERRY_LEAVES, CHERRY_SAPLING, CHISELED_QUARTZ_BLOCK,
    CHISELED_STONE_BRICKS, CHORUS_FLOWER, CLAY, CLOSED_EYEBLOSSOM, COAL_BLOCK, COAL_ORE,
    COARSE_DIRT, COBBLED_DEEPSLATE, COBBLESTONE_SLAB, COBBLESTONE_STAIRS, COBBLESTONE_WALL,
    COPPER_BLOCK, CORNFLOWER, CRACKED_DEEPSLATE_TILES, CRACKED_STONE_BRICKS, CRIMSON_FUNGUS,
    CRIMSON_NYLIUM, CRIMSON_ROOTS, CRYING_OBSIDIAN, CUT_COPPER, CUT_COPPER_SLAB, CUT_COPPER_STAIRS,
    CYAN_CONCRETE, CYAN_CONCRETE_POWDER, CYAN_TERRACOTTA, CYAN_WOOL, DANDELION,
    DARK_OAK_LEAVES, DARK_OAK_SAPLING, DEAD_BRAIN_CORAL_BLOCK, DEAD_FIRE_CORAL_BLOCK,
    DEAD_HORN_CORAL_FAN, DEAD_TUBE_CORAL_BLOCK, DEEPSLATE_COAL_ORE, DEEPSLATE_DIAMOND_ORE,
    DEEPSLATE_EMERALD_ORE, DEEPSLATE_LAPIS_ORE, DEEPSLATE_REDSTONE_ORE, DIAMOND_BLOCK,
    DIAMOND_ORE, DIORITE, DIRT_PATH, DRIPSTONE_BLOCK, EMERALD_ORE, EXPOSED_COPPER,
    EXPOSED_CUT_COPPER, EXPOSED_CUT_COPPER_SLAB, EXPOSED_CUT_COPPER_STAIRS, FERN,
    FIRE_CORAL_BLOCK, FLOWERING_AZALEA, FLOWERING_AZALEA_LEAVES, FROSTED_ICE,
    GILDED_BLACKSTONE, GOLD_BLOCK, GRANITE, GRASS, GRASS_PATH, GRAY_CONCRETE,
    GRAY_CONCRETE_POWDER, GRAY_GLAZED_TERRACOTTA, GRAY_TERRACOTTA, GRAY_WOOL,
    GREEN_CONCRETE, GREEN_CONCRETE_POWDER, GREEN_TERRACOTTA, GREEN_WOOL, HANGING_ROOTS,
    IRON_ORE, JUNGLE_LEAVES, JUNGLE_SAPLING, LAPIS_ORE, LARGE_AMETHYST_BUD, LARGE_FERN,
    LIGHT_BLUE_CONCRETE, LIGHT_BLUE_CONCRETE_POWDER, LIGHT_BLUE_TERRACOTTA, LIGHT_BLUE_WOOL,
    LIGHT_GRAY_CONCRETE, LIGHT_GRAY_CONCRETE_POWDER, LIGHT_GRAY_WOOL, LILAC, LILY_OF_THE_VALLEY,
    LILY_PAD, LIME_CARPET, LIME_CONCRETE, LIME_CONCRETE_POWDER, LIME_GLAZED_TERRACOTTA,
    LIME_SHULKER_BOX, LIME_TERRACOTTA, LIME_WOOL, MAGENTA_CONCRETE, MAGENTA_CONCRETE_POWDER,
    MAGENTA_WOOL, MANGROVE_LEAVES, MANGROVE_PROPAGULE, MANGROVE_SLAB, MEDIUM_AMETHYST_BUD,
    MELON_STEM, MOSS_BLOCK, MOSSY_COBBLESTONE, MOSSY_COBBLESTONE_SLAB, MOSSY_COBBLESTONE_WALL,
    MOSSY_STONE_BRICK_WALL, MUSHROOM_STEM, MYCELIUM, NETHER_QUARTZ_ORE, NETHER_SPROUTS,
    NETHER_PORTAL, NETHER_WART_BLOCK, NETHERITE_BLOCK, NOTE_BLOCK, OAK_SAPLING, OPEN_EYEBLOSSOM,
    PACKED_MUD,
    ORANGE_CONCRETE_POWDER, ORANGE_TERRACOTTA, ORANGE_TULIP, ORANGE_WOOL, OXEYE_DAISY,
    OXIDIZED_COPPER, OXIDIZED_CUT_COPPER, OXIDIZED_CUT_COPPER_SLAB, OXIDIZED_CUT_COPPER_STAIRS,
    PALE_OAK_LEAVES, PALE_OAK_SAPLING, PEONY, PINK_CONCRETE, PINK_PETALS, PINK_TULIP,
    PITCHER_CROP, PITCHER_PLANT, PODZOL, POLISHED_ANDESITE, POLISHED_ANDESITE_STAIRS,
    POLISHED_DEEPSLATE, POLISHED_DIORITE, POPPY, POWDER_SNOW, PUMPKIN_STEM,
    PURPLE_GLAZED_TERRACOTTA, PURPUR_BLOCK, QUARTZ_BLOCK, QUARTZ_STAIRS, RAW_COPPER_BLOCK,
    RAW_GOLD, RAW_IRON, RAW_GOLD_BLOCK, RAW_IRON_BLOCK, RED_CONCRETE, RED_CONCRETE_POWDER, RED_GLAZED_TERRACOTTA,
    RED_MUSHROOM, RED_MUSHROOM_BLOCK, RED_SANDSTONE_SLAB, RED_STAINED_GLASS, RED_TERRACOTTA,
    RED_TULIP, RED_WOOL, REDSTONE_BLOCK, REDSTONE_ORE, ROSE_BUSH, SCULK, SHORT_GRASS,
    SMALL_AMETHYST_BUD, SMALL_DRIPLEAF, SMOOTH_BASALT, SMOOTH_QUARTZ, SMOOTH_SANDSTONE,
    SPAWNER,
    SMOOTH_STONE, SMOOTH_STONE_SLAB, SOUL_SAND, SPORE_BLOSSOM, SPRUCE_LEAVES,
    SPRUCE_SAPLING, SPRUCE_WOOD, STONE_BRICK_SLAB, STONE_BRICK_STAIRS, STONE_BRICKS,
    STONE_SLAB, STRIPPED_DARK_OAK_WOOD, STRIPPED_MANGROVE_WOOD, SUNFLOWER,
    SWEET_BERRY_BUSH, TORCHFLOWER, TORCHFLOWER_CROP, TRAPPED_CHEST, TUFF, TWISTING_VINES_PLANT,
    WARPED_FUNGUS, WARPED_HYPHAE, WARPED_ROOTS, WAXED_COPPER_BLOCK, WAXED_CUT_COPPER,
    WAXED_CUT_COPPER_SLAB, WAXED_CUT_COPPER_STAIRS, WAXED_EXPOSED_COPPER,
    WAXED_EXPOSED_CUT_COPPER, WAXED_EXPOSED_CUT_COPPER_SLAB, WAXED_EXPOSED_CUT_COPPER_STAIRS,
    WAXED_OXIDIZED_COPPER, WAXED_OXIDIZED_CUT_COPPER, WAXED_OXIDIZED_CUT_COPPER_SLAB,
    WAXED_OXIDIZED_CUT_COPPER_STAIRS, WAXED_WEATHERED_COPPER, WAXED_WEATHERED_CUT_COPPER,
    WAXED_WEATHERED_CUT_COPPER_SLAB, WAXED_WEATHERED_CUT_COPPER_STAIRS, WEATHERED_COPPER,
    WEATHERED_CUT_COPPER, WEATHERED_CUT_COPPER_SLAB, WEATHERED_CUT_COPPER_STAIRS,
    WATER_BUCKET, WEEPING_VINES_PLANT, WHITE_CONCRETE, WHITE_CONCRETE_POWDER, WHITE_TULIP, WHITE_WOOL,
    WILDFLOWERS, WITHER_ROSE, YELLOW_CONCRETE, YELLOW_GLAZED_TERRACOTTA,
    YELLOW_SHULKER_BOX, YELLOW_TERRACOTTA, YELLOW_WOOL, ALLIUM, AZALEA, AZALEA_LEAVES,
    ACACIA_LEAVES, ACACIA_LOG, ACACIA_SAPLING, AZURE_BLUET, BAMBOO, BAMBOO_SAPLING,
    BIG_DRIPLEAF_STEM, BIRCH_LEAVES, BIRCH_LOG, BIRCH_SAPLING,
    BARREL, BREWING_STAND, CARTOGRAPHY_TABLE, CHIPPED_ANVIL, COPPER_INGOT,
    COBWEB, DAMAGED_ANVIL, DARK_OAK_LOG, ENCHANTING_TABLE, END_GATEWAY,
    GLOW_LICHEN, GRINDSTONE, LOOM, NETHERITE_INGOT, SHULKER_BOX, SMITHING_TABLE,
    JUNGLE_LOG, OAK_LOG, SPRUCE_LOG;

    public static Material getMaterial(String name) {
        if (name == null) return null;
        try {
            return valueOf(name.trim().toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException ignored) {
            return null;
        }
    }

    public static Material matchMaterial(String name) {
        return getMaterial(name);
    }

    public BlockData createBlockData() {
        if (this == FIRE || this == SOUL_FIRE) return new Fire(this);
        return (this == WATER || this == LAVA || this == LIGHT || name().contains("CAULDRON")) ? new Levelled(this) : new BlockData(this);
    }

    public BlockData createBlockData(Consumer<BlockData> consumer) {
        BlockData data = createBlockData();
        consumer.accept(data);
        return data;
    }

    public boolean isSolid() {
        if (isAir() || this == WATER || this == LAVA || this == FIRE || this == SOUL_FIRE || this == LIGHT)
            return false;
        String name = name();
        if (name.endsWith("_BUTTON") || name.endsWith("_DOOR") || name.endsWith("_TRAPDOOR")) return false;
        if (name.endsWith("_TORCH") || name.endsWith("_SAPLING") || name.endsWith("_FUNGUS") || name.endsWith("_ROOTS"))
            return false;
        if (name.endsWith("_VINES") || name.endsWith("_VINES_PLANT") || name.endsWith("_PETALS")) return false;
        if (name.endsWith("_CROP") || name.endsWith("_STEM")) return false;
        return switch (this) {
            case LADDER, VINE, KELP, KELP_PLANT, SEAGRASS, TALL_SEAGRASS, TALL_GRASS, SHORT_GRASS,
                 GRASS, FERN, LARGE_FERN, SUGAR_CANE, WHEAT, BEETROOTS, CARROTS, POTATOES,
                 MELON_STEM, PUMPKIN_STEM, PITCHER_CROP, PITCHER_PLANT, TORCHFLOWER_CROP,
                 BROWN_MUSHROOM, RED_MUSHROOM, DANDELION, POPPY, BLUE_ORCHID, ALLIUM, AZURE_BLUET,
                 RED_TULIP, ORANGE_TULIP, WHITE_TULIP, OXEYE_DAISY, CORNFLOWER, LILY_OF_THE_VALLEY,
                 WITHER_ROSE, SUNFLOWER, LILAC, ROSE_BUSH, PEONY, WILDFLOWERS, DEAD_HORN_CORAL_FAN,
                 BIG_DRIPLEAF, SMALL_DRIPLEAF, HANGING_ROOTS, NETHER_SPROUTS, SPORE_BLOSSOM,
                 SWEET_BERRY_BUSH, TWISTING_VINES_PLANT, WEEPING_VINES_PLANT, POWDER_SNOW,
                 SNOW, BUBBLE_COLUMN, LEVER, REDSTONE_WALL_TORCH, SOUL_TORCH, TORCH -> false;
            default -> true;
        };
    }

    public boolean isFlammable() {
        return false;
    }

    public boolean isBurnable() {
        return isFlammable();
    }

    public boolean isInteractable() {
        return false;
    }

    public boolean isOccluding() {
        return isSolid();
    }

    public boolean isAir() {
        return this == AIR || this == CAVE_AIR || this == VOID_AIR;
    }

    public float getBlastResistance() {
        return isSolid() ? 1 : 0;
    }

    public Object handle() {
        return this;
    }
}
